version: '3.9'

services:
  postgres:
    image: postgres:14.7
    environment:
      - "POSTGRES_DB=employees"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
